export const CastEvents = {
  LIST_DEVICES: "LIST_DEVICES",
  SET_CAST_DEVICE: "SET_CAST_DEVICE",
  PLAY_ON_CAST: "PLAY_ON_CAST",
  STOP_CALLBACK: "STOP_CALLBACK",
  RESUME: "RESUME",
  STOP: "STOP",
  PAUSE: "PAUSE",
  SEEK: "SEEK",
  STATUS: "STATUS",
};
